import "@/app/styles/portfolio.css";
import type { Metadata } from "next";
import { PageWrapper } from "../components/PageWrapper"

export const metadata: Metadata = {
  title: "Robert A. Morrison - Projects",
  description: "Generated by create next app",
};

const Projects = () => {
    return(
        <PageWrapper>
            <section>
                <h1>Projects Page</h1>
                <p className="project-paragraph">Work in progress...</p>
            </section>
        </PageWrapper>
    )
}
export default Projects